### ISSUE TITLE
core.fact.j2 throws exception

### ISSUE THREAD

**Issue by cultcom** [debops/ansible-core#27] opened 2017-03-21 14:19 UTC
in line 80:
```
admin_users.extend
```
this leads to an exception:

```
root@deb-db01:/etc/ansible/facts.d# ./core.fact 
Traceback (most recent call last):
  File "./core.fact", line 50, in <module>
    admin_users.extend(output['admin_users'])
AttributeError: 'set' object has no attribute 'extend'
```

I guess this should be changed to
```
admin_users.union
```

**Comment by drybjed** [comment] 2017-03-21 14:27
Confirmed, it's a bug. I guess that's the reason I had some issues with the `core.fact` script earlier on Travis... I'll check it out ASAP. Thanks for the heads up!

**Comment by drybjed** [comment] 2017-03-21 19:23
Should be fixed now. Closing.

**Closed by drybjed** 2017-03-21 19:23 UTC
Labels: bug
